<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SIMS_Assignment</RootNamespace>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Tests\SIMS_Assignment.Tests\SIMS_Assignment.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
  </ItemGroup>

</Project>
